### ISSUE TITLE
Selling with wand shows as autosell

### ISSUE THREAD

**Issue by mathiashjelmer** [jbettaque/FancyGens-Bugtracker#7]
Selling with wand shows the message for auto sell:
![image](https://user-images.githubusercontent.com/63245440/159822897-ed1f178b-9d39-4391-82bb-75b7707e8a43.png)
Also multipliers are additive, not multiplicative. So with a prestige multi of 12x and a 3x wand. You get 15x not 36x

**Comment by jbettaque** [comment]
fixed in next update
